"""Nombre descriptivo de cada CPNM (código de 4 caracteres de plant.dat)
según la base vegetal estándar de SWAT2012 -- pedido explícito del usuario
para el wizard de NbS: mostrar significado, no solo el acrónimo, al elegir
una cobertura existente.

Tomado de la lista de referencia del proyecto (CropLu.txt, 127 coberturas
de la base vegetal estándar). Es solo para enriquecer la UI: si el
plant.dat real de un proyecto puntual tiene un CPNM que no está en esta
tabla (base vegetal personalizada), se muestra el CPNM tal cual -- nunca
se usa esta tabla como fuente de verdad de qué coberturas existen en el
proyecto (eso siempre se lee del plant.dat real, ver
swat_io.plant.parser).
"""
from __future__ import annotations

CPNM_NAMES: dict[str, str] = {
    "AGRL": "Agricultural Land-Generic",
    "AGRR": "Agricultural Land-Row Crops",
    "AGRC": "Agricultural Land-Close-grown",
    "ORCD": "Orchard",
    "HAY": "Hay",
    "FRST": "Forest-Mixed",
    "FRSD": "Forest-Deciduous",
    "FRSE": "Forest-Evergreen",
    "WETL": "Wetlands-Mixed",
    "WETF": "Wetlands-Forested",
    "WETN": "Wetlands-Non-Forested",
    "PAST": "Pasture",
    "SPAS": "Summer Pasture",
    "WPAS": "Winter Pasture",
    "RNGE": "Range-Grasses",
    "RNGB": "Range-Brush",
    "SWRN": "Southwestern US (Arid) Range",
    "WATR": "Water",
    "CORN": "Corn",
    "CSIL": "Corn Silage",
    "SCRN": "Sweet Corn",
    "EGAM": "Eastern Gamagrass",
    "GRSG": "Grain Sorghum",
    "SGHY": "Sorghum Hay",
    "JHGR": "Johnsongrass",
    "SUGC": "Sugarcane",
    "SWHT": "Spring Wheat",
    "WWHT": "Winter Wheat",
    "DWHT": "Durum Wheat",
    "RYE": "Rye",
    "BARL": "Spring Barley",
    "OATS": "Oats",
    "RICE": "Rice",
    "PMIL": "Pearl Millet",
    "TIMO": "Timothy",
    "BROS": "Smooth Bromegrass",
    "BROM": "Meadow Bromegrass",
    "FESC": "Tall Fescue",
    "BLUG": "Kentucky Bluegrass",
    "BERM": "Bermudagrass",
    "CWGR": "Crested Wheatgrass",
    "WWGR": "Western Wheatgrass",
    "SWGR": "Slender Wheatgrass",
    "RYEG": "Italian (Annual) Ryegrass",
    "RYER": "Russian Wildrye",
    "RYEA": "Altai Wildrye",
    "SIDE": "Sideoats Grama",
    "BBLS": "Big Bluestem",
    "LBLS": "Little Bluestem",
    "SWCH": "Alamo Switchgrass",
    "INDN": "Indiangrass",
    "ALFA": "Alfalfa",
    "CLVS": "Sweetclover",
    "CLVR": "Red Clover",
    "CLVA": "Alsike Clover",
    "SOYB": "Soybean",
    "CWPS": "Cowpeas",
    "MUNG": "Mung Beans",
    "LIMA": "Lima Beans",
    "LENT": "Lentils",
    "PNUT": "Peanut",
    "FPEA": "Field Peas",
    "PEAS": "Garden or Canning Peas",
    "SESB": "Sesbania",
    "FLAX": "Flax",
    "COTS": "Upland Cotton (stripper harvest)",
    "COTP": "Upland Cotton (picker harvest)",
    "TOBC": "Tobacco",
    "SGBT": "Sugarbeet",
    "POTA": "Potato",
    "SPOT": "Sweetpotato",
    "CRRT": "Carrot",
    "ONIO": "Onion",
    "SUNF": "Sunflower",
    "CANP": "Spring Canola-Polish",
    "CANA": "Spring Canola-Argentine",
    "ASPR": "Asparagus",
    "BROC": "Broccoli",
    "CABG": "Cabbage",
    "CAUF": "Cauliflower",
    "CELR": "Celery",
    "LETT": "Head Lettuce",
    "SPIN": "Spinach",
    "GRBN": "Green Beans",
    "CUCM": "Cucumber",
    "EGGP": "Eggplant",
    "CANT": "Cantaloupe",
    "HMEL": "Honeydew Melon",
    "WMEL": "Watermelon",
    "PEPR": "Bell Pepper",
    "STRW": "Strawberry",
    "TOMA": "Tomato",
    "APPL": "Apple",
    "PINE": "Pine",
    "OAK": "Oak",
    "POPL": "Poplar",
    "MESQ": "Honey Mesquite",
    "GRAP": "Vineyard",
    "WBAR": "Winter Barley",
    "OILP": "Oil Palm",
    "RUBR": "Rubber Trees",
    "BANA": "Bananas",
    "TEFF": "Eragrostis Teff",
    "COFF": "Coffee",
    "PTBN": "Pinto Beans",
    "ALMD": "Almonds",
    "GRAR": "Garrigue",
    "OLIV": "Olives",
    "ORAN": "Orange",
    "SEPT": "Septic Area",
    "COCO": "Coconut",
    "CASH": "Cashews",
    "PAPA": "Papayas",
    "PINP": "Pineapple",
    "PLAN": "Plantains",
    "PEPP": "Peppers",
    "WILL": "Willow",
    "BARR": "Barren",
    "EUCA": "Eucalyptus",
    "CASS": "Cassava",
    "RADI": "Radish",
    "MINT": "Mint",
    "COCB": "Cockle Burr",
    "COCT": "Cocoa Tree",
    "PART": "Parthenium",
    "WALN": "Walnut",
    "MAPL": "Maple",
}


def name_for(cpnm: str) -> str:
    """Nombre descriptivo de ``cpnm``, o el propio código si no está en la
    tabla (p. ej. una cobertura ya personalizada en el plant.dat real)."""
    return CPNM_NAMES.get(cpnm.upper(), cpnm)
